### ISSUE TITLE
커밋 코멘트 이슈

### ISSUE THREAD

**Issue by kongchu2** [kan58dan/MusicSort#1]
커밋 코멘트에 엄준식이 뭡니까 엄준식이...
이건 진짜 아니라고 생각합니다.
정상적인 작명센스를 보여주십시오

**Comment by kongchu2** [comment]
이 커밋 메세지 때문에 개발 진행에 큰 난항이 예상됩니다.
 지금 당장 수정해 주세요.

**Comment by kongchu2** [comment]
엄준식은좀아니지엄준식은

**Comment by kan58dan** [comment]
엄
준
식

**Comment by kongchu2** [comment]
주식으로일가족전재산다날려먹은광교강응찬

**Comment by kongchu2** [comment]
광교기숙사케찹지배자강응찬

**Comment by kongchu2** [comment]
비트코인으로일가족전재산을날려버린광교의아들강응찬
